name: Server Deploy MASTER

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: set up CONFIG
        env:
          LOCAL_PROPERTIES: ${{ secrets.CONFIG }}
        run: echo "CONFIG" > src/main/resources/application.conf

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: stslex/kproselection:latest
          platforms: linux/amd64

      - name: SSH Command
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SERVER_SSH }}
          script: |
            docker pull stslex/kproselection
            docker kill $(docker ps -q)
            docker remove $(docker ps -a -f status=exited -q)
            docker run -d -p 80:8080 --restart always stslex/kproselection:latest
            docker run -d -p 8080:8080 --restart always stslex/kproselection:test
